### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by roblabla** [core-error/core-error#2]
- The crate should be tested on all minor versions of rust from 1.6.0 with no-default-features
- The crate should be tested on all minor versions of rust from 1.36.0 with alloc feature
- 1.0.0 should be tested with std feature enabled just to make sure that works.
- Ensure it builds with `-Zminimal-versions`.

**Comment by leo60228** [comment]
I'd say we should also run on the latest nightly with both no features and alloc, and possibly have a hardcoded list of nightlies with relevant changes.

**Comment by shepmaster** [comment]
As you have some dependencies, please ensure to run a test with `-Zminimal-versions` to ensure that your version requirement is always valid.

**Comment by leo60228** [comment]
I'm 99% sure this is completed with https://github.com/core-error/core-error/commit/eb1f12c781294484f1bdbd92243a435a7656be8e, but I'm going to wait for it to pass to be sure.

**Comment by leo60228** [comment]
Completed in af85bf5fc947c9f864e417c0f876848c3b78c617.
