### ISSUE TITLE
impl core_error::Error on alloc errors when alloc feature is enabled

### ISSUE THREAD

**Issue by roblabla** [core-error/core-error#3]
- alloc::AllocErr (nightly-only, how do we deal with that?)
- alloc::LayoutErr
- fmt::Error
- ...

**Comment by leo60228** [comment]
> nightly-only, how do we deal with that?

rustc_version provides the commit-date from the compiler, as well as the channel. We could compare the date and make sure the channel is nightly if it's from before stabilization, but that seems brittle. We could also copy the definition of `probe` from the autocfg crate. That might impact compile times, though.

**Comment by leo60228** [comment]
Looks like the version_check crate you're already using has functions for both of these (comparing the date and checking if it's nightly, I mean).

**Comment by roblabla** [comment]
I'll ignore nightly-only stuff for now, see #9 .

**Comment by roblabla** [comment]
done with https://github.com/core-error/core-error/commit/da503ceef33c80f0c8e6ebd3eb74580e04defc4a and https://github.com/core-error/core-error/commit/35b5012610ccab48f88c73b91486576736d5b24a
