### ISSUE TITLE
Investigate allowing downcasting

### ISSUE THREAD

**Issue by roblabla** [core-error/core-error#4]
rust provides functions like `is`, `downcast_ref` and `downcast_mut` on `dyn Error + 'static`, and additionally provides `downcast` on Error. We should check out if we can provide that API too.

**Comment by leo60228** [comment]
We can't do this if the only thing the crate provides is Error (it's only sound if `is` is provided by a trait that can't be implemented by other crates). We can still do this by copy/pasting the example implementation of TypeInfo from [my RFC](https://github.com/leo60228/rfcs/blob/master/text/0000-typeinfo.md).

**Comment by roblabla** [comment]
Implemented with https://github.com/core-error/core-error/commit/19209b21af87eef20b663f541e1f3ce2f79ddead

Just needs some documentation touchups now.

**Comment by roblabla** [comment]
Done with https://github.com/core-error/core-error/commit/2ea461f5aaf49cbe551cf11b6d951421c62081e8 and https://github.com/core-error/core-error/commit/0ddb4fc0ed7f97ea7166e2a52fad71d2db9a5b2b
