### ISSUE TITLE
Explain how to properly use core-error in the README/root doc.

### ISSUE THREAD

**Issue by roblabla** [core-error/core-error#5]
We should ensure we have clear integration docs everywhere. In particular, it's important to emphasis that libraries using the `Error` trait to implement it on their own errors should specify `no-default-features = true`!

We should properly document the features, and how each type of user should use them.

**Comment by shepmaster** [comment]
I've been thinking about similar points for SNAFU and I think this decision should depending on a crate's desired primary location in the dependency tree. The more foundational a crate is, the more likely it should have fewer default features.

For SNAFU, my back-of-mind idea is to create two meta features: `library` and `application`. I'd then take everything out of the default feature set and guide people to choosing one or the other.

**Comment by roblabla** [comment]
🤔 this might be a bit tricky. Here's the scenario I envision:

Application depends on library using snafu, doesn't directly depend on core-error
- snafu should forward an std and alloc feature to core-error to ensure it builds in the right mode.
- Library should expose an `std` and a (not-default) `alloc` feature it forwards them to snafu.
- The std feature in the library/snafu should *probably* be the default. This way, std users aren't surprised, while no_std user will fail fast (albeit with a super confusing error).

core-error probably won't default to enable the std feature. This is because it wouldn't benefit anybody. Instead, it should have an `alloc` and `std` features, and libraries using core-error should do it like so:

```toml
[dependencies]
core-error = "1.0.0"

[features]
std = ["core-error/std"]
alloc = ["core-error/alloc"]

# If this makes sense for this specific crate:
default = ["std"]
```

Applications should very rarely (if ever) depend on core-error directly, so I don't think having an `application` meta-feature would help.

---

The failure mode I'm trying to avoid is when a no_std binary ends up with std in its dependency. This causes confusing, hard-to-debug situations where you end up chasing the dep tree to find which library accidentally forgot to turn off the default features.

On the other side, the failure mode of a library using the "wrong" Error trait because it didn't activate the feature isn't a huge deal, I feel. Either it will work "fine", or it will quickly cause an error saying a type doesn't implement std::Error, which will be an immediate sign that the crate that type belongs to is messing up its features.

This failure mode is much easier to quickfix by the downstream crate (by adding a dependency on core-error and manually activating the std feature) and fix "properly" in the offending library (by adding the required "proxy" features).

**Comment by leo60228** [comment]
If this documentation is insufficient, I'll reopen this issue.
