### ISSUE TITLE
Consider eliminating the deprecated methods

### ISSUE THREAD

**Issue by dtolnay** [core-error/core-error#7]
I understand the motivation to mirror std::error::Error as closely as possible, but is there any benefit to including `description` and `cause` methods? Those should definitively never appear in new code, neither in impls nor called.

**Comment by shepmaster** [comment]
Since this trait is effectively new, there can be no current users of those specific methods, so removing them should be Kosher. When `std` is enabled, the deprecated methods would be re-added anyway.

**Comment by roblabla** [comment]
I'm afraid that removing the functions might cause compatibility trouble. If someone wants their crate to compile on rust 1.26 and under, they *have* to specify a `description` function with the `std::error::Error`. If we remove the `description` function from our trait, `core-error` won't be drop-in compatible on those old rust versions, which I highly value.

The default implementation of `description()` was added in Rust 1.27.0, released in Jun 21, 2018. I don't really have any information on whether there is anyone still using those old rust version.

**Comment by dtolnay** [comment]
It can be added later on if someone makes a compelling case for why they need it.

**Comment by roblabla** [comment]
I removed both `cause` and `description` in https://github.com/core-error/core-error/commit/5b9e812184c797b64235fe96239117d278b0f2bc and https://github.com/core-error/core-error/commit/6a6fd492095325423554601cf40c1e5bddc6b348. They can be added back later as a default method if the need arises.

**Comment by CryZe** [comment]
For snafu to adopt this crate, would they be fine with not implementing those methods anymore? @shepmaster 

I guess it might just only implement them when the std feature is active.

**Comment by leo60228** [comment]
I'm pretty sure not implementing them in no_std would be a breaking change. I'm going to re-add them, unless there are objections.

**Comment by dtolnay** [comment]
I object -- crates for which switching to core-error would be a breaking change can release a major version.

**Comment by leo60228** [comment]
I've re-eliminated them.
